// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektOOP.Modeli;

#nullable disable

namespace ProjektOOP.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20240309175627_DrugaMigracija")]
    partial class DrugaMigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("ProjektOOP.Modeli.Useri_i_paswordi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ime_zaposlenika")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password_zaposlenika")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("prezime_zaposlenika")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username_zaposlenika")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Zaposlenici");
                });
#pragma warning restore 612, 618
        }
    }
}
